/particle_filter:
  ros__parameters:
    num_particles: 250
    x_range_m: [-2.25, 2.25]
    y_range_m: [-2.25, 2.25]
    theta_range_deg: [0, 360]
    odom_topic: '/odom_vel'
    predict_noise: [0.015,0.005]
    update_noise: 0.125
    update_method: 'gaussian'
    cone_angle_deg: 10
    resampling_method: 'systematic'
    map_pkl_file: 'turtlebot3_dqn_stage4u_grid_0.25_3_3.pkl'
    map_pgm_file: 'turtlebot3_dqn_stage4u.pgm'
    map_yaml_file: 'turtlebot3_dqn_stage4.yaml'
    plot_enabled: True