/histogram_filter:
  ros__parameters:
    histogram_bins: 20
    histogram_range_m: [0.12, 3.5]
    histogram_comparison: 'manhattan'
    map_pkl_file: 'turtlebot3_dqn_stage4_0.1.pkl'
    plot_enabled: True